### ISSUE TITLE
cyclic dependency between PyOCD and PyOCD_PEMicro

### ISSUE THREAD

**Issue by maxhbr** [pyocd/pyOCD#1152]
- PyOCD depends on PyOCD_PEMicro in https://github.com/pyocd/pyOCD/blob/e8797c61083d320a665cd5832ee346d8e074b3ae/setup.py#L77
- PyOCD_PEMicro depends on PyOCD in https://github.com/pyocd/pyocd-pemicro/blob/38c4ee20c433cf91f9426cd5dca4049a78d6bb35/setup.py#L77

This is a (probably accidental) cyclic dependency prevents packaging of the tool in something like NixOS.

**Comment by flit** [comment]
D'oh! It's actually not accidental. The dependency of pyocd-pemicro on pyocd was added recently since technically, pyocd-pemicro is useless without pyocd. However, we want pyocd to automatically install pyocd-pemicro as a dependency.

Thanks for alerting us. I'll remove the dependency in pyocd-pemicro.

**Comment by flit** [comment]
Just released pyocd-pemicro [v1.0.5](https://github.com/pyocd/pyocd-pemicro/releases/tag/v1.0.5) with the pyocd dependency removed.
